# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ccd039aef59cd99b8f88ecbe432d03c5fa938b8851e826a46864a70a93f588126521f1334727ab40fc4da5ad9f46a9b0ba93077da4068de72712747a1712240

test:
  secret_key_base: f89b0434743301a7ca9dd7d2424e6d74c53b2300fdbfa801b23e651d6b40b8721260e1e1949dda73adff38f6577a2dbec5ad37432d2be7d28c8a1e2739aaca2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
